# Site settings
title: 'Meerabelle Jesuthasan' # Your Title
tagline: 'Writing. Researching. Dramatizing.' # A brief tagline for your site
sidebar_image: /images/cover1.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: /meerabellejesuthasan # the subpath of your site, e.g. /blog/
