# Site settings
title: 'Kadal Jesuthasan' # Your Title
tagline: 'journalist and fact-checker' # A brief tagline for your site
sidebar_image: /images/kadal jesuthasan.png

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: # the subpath of your site, e.g. /blog/

domain: meerabellejesuthasan.com
